//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\mssqllocaldb;Initial Catalog=TrentsTroubleMakersDb;Integrat" +
            "ed Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;A" +
            "pplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string TrentsTroublemakersConnectionString {
            get {
                return ((string)(this["TrentsTroublemakersConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=CWROG; Database=Troublemakers;Integrated Security=SSPI;")]
        public string TrentsTroublemakersConnectionStringCW {
            get {
                return ((string)(this["TrentsTroublemakersConnectionStringCW"]));
            }
            set {
                this["TrentsTroublemakersConnectionStringCW"] = value;
            }
        }
    }
}
